# Generated by Django 4.1.2 on 2023-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('club_image', models.ImageField(blank=True, null=True, upload_to='club_images/')),
            ],
        ),
    ]
